# docker-compose.yaml
services:
  app:
    build: .
    ports:
      - 5000:5000
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /
        - action: rebuild
          path: .src/requiments.txt
